### ISSUE TITLE
consult not the real issue

### ISSUE THREAD

**Issue by JohnnyHan** [xiangli13/circle-loss#1]
hi committer,  thanks for sharing your work！
 but confiused with the comment of the CircleLoss 
"Inputs is a list of three tensors, the first one contains the positive feature samples, the second contains the negative feature samples, and the third contains the query feartures. "

The features I got from the model  and surely with the labels(just like , 1,2,3... not the one_hot method). these are only two variabels here , inputs are array include three variables.

how could i use this inputs in my classification task.

**Comment by xiangli13** [comment]
Hi,
I think the earlier commit of the implementation (https://github.com/TinyZeaMays/CircleLoss/commit/edf32c4223580ca849caa46d04f3eb9650870b9e) from the author can give you some clue of this issue/problem. The author used "scatter", "gather", and "crossentropy" to make the code work for your use case.
Or, you can make a data generator to generate pair-wise data with the data you have.

Will give you a follow-up update on this, if I got time to modify a new version for this data-label fashion.
